### ISSUE TITLE
Running yarn docker:dev results in error while composing node-app

### ISSUE THREAD

**Issue by enrico3498** [saisilinus/node-express-mongoose-typescript-boilerplate#28]
# Problem: 
When I try to dockerize the application the composing errors on the node-app part. No directory is created and nothing happens. Besides the console showing the key word error not further stack trace is displayed. So I would be interested if this is a general issue or if my environment is the issue.

# Environment:
| Module | Version |
|------|---|
| node | v16.15.1 |
| yarn | v1.22.19 |
| npm | v8.18.0 |

# Device
| | |
| ----- | --- |
| Type | MacBook Pro (16", 2021) |
| OS | macOS Monterey v12.6 |
| Chip | Apple M1 Pro |

# Steps to reproduce issue
```
$ git clone https://github.com/saisilinus/node-express-mongoose-typescript-boilerplate.git
$ yarn install
$ cp .env.example .env
$ yarn docker:dev
```

**Comment by saisilinus** [comment]
I am also getting an error on my end. I meant to fix the docker issues but somehow forgot about it. I will start working on it ASAP but will appreciate all the help you can provide
